# Generated by Django 5.1.6 on 2025-02-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(help_text='Įveskite produktų grupės pavadinimą', max_length=100, verbose_name='Produktų grupės')),
            ],
            options={
                'verbose_name': 'Produktų grupė',
                'verbose_name_plural': 'Produktų grupės',
            },
        ),
        migrations.CreateModel(
            name='RentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('summary', models.TextField(help_text='Trumpas produkto aprašymas', max_length=1000, verbose_name='Aprašymas')),
                ('inv_no', models.CharField(max_length=100, verbose_name='Invenorizacijos numeris')),
                ('group', models.ManyToManyField(help_text='parinkite kokia grupei priklauso produktas', to='rent.rentgroup', verbose_name='Produktų grupės')),
            ],
            options={
                'verbose_name': 'Prouktas',
                'verbose_name_plural': 'Produktai',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Bus prieinamas')),
                ('status', models.CharField(blank=True, choices=[('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima paimti'), ('r', 'Rezervuota')], default='a', help_text='Statusas', max_length=1)),
                ('rent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_instance', to='rent.rentproduct', verbose_name='Produktas')),
            ],
            options={
                'verbose_name': 'Produkto kopija',
                'verbose_name_plural': 'Produkto kopijos',
                'ordering': ['due_date'],
            },
        ),
    ]
