# Generated by Django 5.1.6 on 2025-03-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite produktų grupės pavadinimą', max_length=100, verbose_name='Produktų grupė')),
            ],
            options={
                'verbose_name': 'Produktų grupė',
                'verbose_name_plural': 'Produktų grupės',
            },
        ),
        migrations.RemoveField(
            model_name='rentproduct',
            name='group',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('description', models.TextField(help_text='Trumpas produkto aprašymas', max_length=1000, verbose_name='Aprašymas')),
                ('group', models.ForeignKey(blank=True, help_text='parinkite kokia grupei priklauso produktas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.group', verbose_name='Produktų grupės')),
            ],
            options={
                'verbose_name': 'Prouktas',
                'verbose_name_plural': 'Produktai',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(help_text='Veskite invenorizacijos numerį', max_length=100, unique=True, verbose_name='Invenorizacijos numeris')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='rent.product', verbose_name='Produktas')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Bus prieinamas')),
                ('is_available', models.BooleanField(default=True)),
                ('condition', models.CharField(blank=True, choices=[('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima paimti'), ('r', 'Rezervuota')], default='a', help_text='Būklė', max_length=1)),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='rent.warehouse', verbose_name='Produktas')),
            ],
            options={
                'verbose_name': 'Produkto kopija',
                'verbose_name_plural': 'Produkto kopijos',
                'ordering': ['due_date'],
            },
        ),
        migrations.DeleteModel(
            name='ProductInstance',
        ),
        migrations.DeleteModel(
            name='RentGroup',
        ),
        migrations.DeleteModel(
            name='RentProduct',
        ),
    ]
