# Generated by Django 5.1.6 on 2025-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_group_remove_rentproduct_group_product_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['due_date'], 'verbose_name': 'Produkto būsena', 'verbose_name_plural': 'Produktų būsenos'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Sandėlys'},
        ),
    ]
