# Generated by Django 5.1.6 on 2025-03-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_status_options_alter_warehouse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['warehouse_product'], 'verbose_name': 'Produkto būsena', 'verbose_name_plural': 'Produktų būsenos'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['inv_no'], 'verbose_name': 'Produktas sandėlyje', 'verbose_name_plural': 'Produktai sandėlyje'},
        ),
        migrations.AddField(
            model_name='status',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='rent.product', verbose_name='Produktas'),
        ),
    ]
