# Generated by Django 5.1.6 on 2025-03-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_status_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['inv_no'], 'verbose_name': 'Produkto būsena', 'verbose_name_plural': 'Produktų būsenos'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='warehouse_product',
        ),
        migrations.AddField(
            model_name='status',
            name='inv_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_product', to='rent.warehouse', verbose_name='Invenorizacijos numeris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Parinkite kokia grupei priklauso produktas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.group', verbose_name='Produktų grupės'),
        ),
        migrations.AlterField(
            model_name='status',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='rent.product', verbose_name='Produktas'),
        ),
    ]
