# Generated by Django 5.1.6 on 2025-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_remove_status_inv_no_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Kiekis', null=True, verbose_name='Kiekis'),
        ),
    ]
