# Generated by Django 5.1.6 on 2025-03-10 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unikalus ID vienodams produktams'),
        ),
    ]
