# Generated by Django 5.1.6 on 2025-03-10 10:07

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_status_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='due_date',
        ),
        migrations.AddField(
            model_name='status',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nuomos pabaigos datas'),
        ),
        migrations.AddField(
            model_name='status',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nuomos pradžios data'),
        ),
        migrations.AlterField(
            model_name='status',
            name='condition',
            field=models.CharField(blank=True, choices=[('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima rezervuoti'), ('r', 'Rezervuota')], default='a', help_text='Būklė', max_length=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, help_text='Unikalus ID vienodams produktams', max_length=22),
        ),
    ]
