# Generated by Django 5.1.6 on 2025-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_remove_status_due_date_status_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Paveikslėlis'),
        ),
    ]
