# Generated by Django 5.1.6 on 2025-03-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='condition',
            field=models.CharField(blank=True, choices=[('n', 'Laikinai neprieinama'), ('i', 'Išnuomota. Tikrinti galimas dienas: '), ('g', 'Galima nuomotis. Tikrinti prieinamumą ateityje: '), ('r', 'Rezervuota')], default='a', help_text='Būklė', max_length=1),
        ),
    ]
