# Generated by Django 5.1.6 on 2025-03-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_alter_status_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='status',
            name='condition',
            field=models.CharField(blank=True, choices=[('n', 'Laikinai neprieinama'), ('i', 'Išnuomota'), ('g', 'Prekę turime sandėlyje.'), ('r', 'Rezervuota')], default='a', help_text='Būklė', max_length=1),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Nuomos pradžios data')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Nuomos pabaigos datas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent.product')),
            ],
        ),
    ]
