# Generated by Django 5.1.6 on 2025-03-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_remove_status_end_date_remove_status_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Klientas'),
        ),
        migrations.AddField(
            model_name='status',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Bus prieinama nuo'),
        ),
    ]
