# Generated by Django 5.1.6 on 2025-03-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_reservation_customer_reservation_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='reservations_status', to='rent.reservation'),
        ),
    ]
