# Generated by Django 5.1.6 on 2025-03-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_status_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='reservations',
        ),
        migrations.AddField(
            model_name='status',
            name='reservations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_status', to='rent.reservation'),
        ),
    ]
