# Generated by Django 5.1.6 on 2025-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_remove_status_reservations_status_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='reservations',
        ),
        migrations.AddField(
            model_name='status',
            name='reservations',
            field=models.ManyToManyField(blank=True, null=True, related_name='reservations_status', to='rent.reservation'),
        ),
    ]
