# Generated by Django 5.1.6 on 2025-03-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_remove_status_reservations_status_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_status', to='rent.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='reservations',
            field=models.ManyToManyField(blank=True, null=True, related_name='status_reservations', to='rent.reservation'),
        ),
    ]
