# Generated by Django 5.1.6 on 2025-03-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_remove_reservation_customer_remove_reservation_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='reservations',
        ),
    ]
