# Generated by Django 5.1.6 on 2025-03-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0020_remove_reservation_status_status_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_status', to='rent.status'),
        ),
    ]
