# Generated by Django 5.1.6 on 2025-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0022_alter_reservation_options_remove_reservation_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='due_back',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Ar darbuotojas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
