# Generated by Django 5.1.6 on 2025-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0025_alter_status_options_alter_status_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Paros nuomos kaina', null=True, verbose_name='Kaina'),
        ),
    ]
